module Skeldeklaracja where

-- Haskell module generated by the BNF converter

import Absdeklaracja
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transIdent :: Ident -> Result
transIdent x = case x of
  Ident str  -> failure x


transProgram :: Program -> Result
transProgram x = case x of
  Progr compund_contents  -> failure x


transCompund_content :: Compund_content -> Result
transCompund_content x = case x of
  ScompContentStm stm  -> failure x
  ScompContentDec dec  -> failure x
  ScompContentExp exp  -> failure x
  ScompContentSpace namespace  -> failure x


transNamespace :: Namespace -> Result
transNamespace x = case x of
  BlockSp compund_contents  -> failure x
  EmptyBlockSp  -> failure x


transDec :: Dec -> Result
transDec x = case x of
  VariableDec variable  -> failure x
  FuncDec function  -> failure x


transType_specifier :: Type_specifier -> Result
transType_specifier x = case x of
  Tbool  -> failure x
  Tint  -> failure x
  Tstring  -> failure x
  Tauto  -> failure x


transDec_base :: Dec_base -> Result
transDec_base x = case x of
  DecBase type_specifier id  -> failure x


transVariable :: Variable -> Result
transVariable x = case x of
  InitDec initialized_variable  -> failure x
  UninitDec uninitialized_variable  -> failure x


transUninitialized_variable :: Uninitialized_variable -> Result
transUninitialized_variable x = case x of
  UninitSimpleTypeDec dec_base  -> failure x
  UninitArr dec_base exp  -> failure x


transInitialized_variable :: Initialized_variable -> Result
transInitialized_variable x = case x of
  InitSimpleTypeDec dec_base initializer  -> failure x
  InitArr dec_base initializers  -> failure x
  InitAutoArr dec_base initializers  -> failure x


transInitializer :: Initializer -> Result
transInitializer x = case x of
  InitExpr exp  -> failure x


transFunction :: Function -> Result
transFunction x = case x of
  NoParamFunc dec_base namespace  -> failure x
  ParamFunc dec_base params namespace  -> failure x


transParam :: Param -> Result
transParam x = case x of
  FuncParam uninitialized_variable  -> failure x


transStm :: Stm -> Result
transStm x = case x of
  SelS selection_stm  -> failure x
  IterS iter_stm  -> failure x
  JumpS jump_stm  -> failure x
  PrintS print_stm  -> failure x


transSelection_stm :: Selection_stm -> Result
transSelection_stm x = case x of
  Sif exp compund_content  -> failure x
  SifElse exp compund_content1 compund_content2  -> failure x
  SswitchOne exp switch_content  -> failure x
  SswitchMany exp switch_contents  -> failure x


transSwitch_content :: Switch_content -> Result
transSwitch_content x = case x of
  SswitchCase exp compund_contents  -> failure x
  SswitchDef compund_contents  -> failure x


transIter_stm :: Iter_stm -> Result
transIter_stm x = case x of
  Swhile exp compund_content  -> failure x
  Sfor exp_or_empty1 exp_or_empty2 exp_or_empty3 compund_content4  -> failure x


transExp_or_empty :: Exp_or_empty -> Result
transExp_or_empty x = case x of
  SemptyExp  -> failure x
  SnonemptyExp exp  -> failure x


transJump_stm :: Jump_stm -> Result
transJump_stm x = case x of
  Scontinue  -> failure x
  Sbreak  -> failure x
  Sreturn exp  -> failure x


transPrint_stm :: Print_stm -> Result
transPrint_stm x = case x of
  SPrint exp  -> failure x


transExp :: Exp -> Result
transExp x = case x of
  Ecomma exp1 exp2  -> failure x
  Eassign lvalue assignment_op exp  -> failure x
  Elor exp1 exp2  -> failure x
  Eland exp1 exp2  -> failure x
  Eeq exp1 exp2  -> failure x
  Eneq exp1 exp2  -> failure x
  Elthen exp1 exp2  -> failure x
  Egrthen exp1 exp2  -> failure x
  Ele exp1 exp2  -> failure x
  Ege exp1 exp2  -> failure x
  Eplus exp1 exp2  -> failure x
  Eminus exp1 exp2  -> failure x
  Etimes exp1 exp2  -> failure x
  Ediv exp1 exp2  -> failure x
  Epreinc lvalue  -> failure x
  Epredec lvalue  -> failure x
  Epreop unary_operator exp  -> failure x
  Epostinc lvalue  -> failure x
  Epostdec lvalue  -> failure x
  Efunk id  -> failure x
  Efunkpar id exps  -> failure x
  Elval lvalue  -> failure x
  Econst constant  -> failure x


transConstant :: Constant -> Result
transConstant x = case x of
  Ebool cbool  -> failure x
  Eint n  -> failure x
  Estring str  -> failure x


transCBool :: CBool -> Result
transCBool x = case x of
  BTrue  -> failure x
  BFalse  -> failure x


transLValue :: LValue -> Result
transLValue x = case x of
  LVar id  -> failure x
  LArrEl id exp  -> failure x


transConstant_expression :: Constant_expression -> Result
transConstant_expression x = case x of
  Especial exp  -> failure x


transUnary_operator :: Unary_operator -> Result
transUnary_operator x = case x of
  Plus  -> failure x
  Negative  -> failure x
  Logicalneg  -> failure x


transAssignment_op :: Assignment_op -> Result
transAssignment_op x = case x of
  Assign  -> failure x
  AssignMul  -> failure x
  AssignDiv  -> failure x
  AssignAdd  -> failure x
  AssignSub  -> failure x



